### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by PianSom** [TotalGriffLock/udmp-jumbo-frames-ppp#1]
There is a typo in line 22 of 11-change-ppp-mtu.sh

Should read :
`if [[ $pinterface =~ $MINTERFACES ]]; then`

(ie you have an erroneous "s", which means the loop fails if there is more than one ppp entry returned by the `ls`)

How quickly does your pppd come back up? I am finding it takes MUCH longer than 5 secs

**Comment by TotalGriffLock** [comment]
Apologies for the late response, Github didn't tell me anyone had opened an issue! I've fixed the typo now, thanks!

My pppd comes back almost instantly on both a UDM-Pro and a UDM-SE, although this may be coincidental. I'll investigate further.

**Comment by TotalGriffLock** [comment]
It seems like the time it takes to come back is ISP dependent, on whether the ISP clears the PPP session immediately on disconnection or waits for it to timeout. If you see a load of messages saying "Timeout waiting for PADO packets" in /var/log/messages then your ISP still thinks your PPPoE link is up and is waiting for it to timeout at their end before allowing you to connect again. pppd should send a PADT command to say it is terminating the session, but I guess it isn't... It looks like this may be fixed in a newer version of rp-pppoe than Unifi is using.
